apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcasedeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: showcaseapp
  template:
    metadata:
      labels:
        app: showcaseapp
    spec:
      containers:
      - name: showcase
        image: tomve/tomvk8sshowcase:v2
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: api/health
            port: 80
          initialDelaySeconds: 10
          failureThreshold: 1
          periodSeconds: 2
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8S_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: K8S_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  name: showcaseservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: showcaseapp